version: "3"

services:
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6378:6378"
  where_watch:
    build:
      context: ./where_watch
    restart: always
    tty: true
    command: "uvicorn main:app --host 0.0.0.0 --port 8006"
    expose:
      - 8006
    environment:
      REDIS: redis://redis:6378/1
      VIRTUAL_HOST: apiwatch.jebzpapy.tk
      VIRTUAL_PORT: 8006
    depends_on:
      - redis
  
  frontend:
    build:
      context: ./frontend
    restart: always
    tty: true
    expose:
      - 3000
    environment:
      API_URL:
      VIRTUAL_HOST: watch.jebzpapy.tk
      VIRTUAL_PORT: 3000
networks:
  default:
    external:
      name: nginx-proxy