version: "3"

services:
  redis:
    image: "redis:alpine"
    restart: always
    command: --port 6378
    expose:
      - 6378
  where_watch:
    build:
      context: ./where_watch
    container_name: where_watch_api
    restart: always
    tty: true
    command: "uvicorn main:app --host 0.0.0.0 --port 8006"
    environment:
      - REDIS=redis://redis:6378
      - VIRTUAL_HOST=watch.jebzpapy.tk
      - LETSENCRYPT_HOST=watch.jebzpapy.tk
      - VIRTUAL_PORT=8006
    depends_on:
      - redis
  worker:
    build: ./where_watch
    command: celery --app worker.worker worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6378
      - CELERY_RESULT_BACKEND=redis://redis:6378
    depends_on:
      - redis
      - where_watch
networks:
  default:
    external:
      name: nginx-proxy
