version: "3"

services:
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=where_watch
      - POSTGRES_PASSWORD=where_watch
      - POSTGRES_DB=where_watch
    expose:
      - 5432
  redis:
    image: "redis:alpine"
    restart: always
    command: --port 6378
    expose:
      - 6378
  app:
    build:
      context: ./app
    container_name: where_watch_app
    image: where_watch_app
    restart: always
    tty: true
    ports:
      - "8006:8006"
    command: "gunicorn --reload app.wsgi:application --bind 0.0.0.0:8006 -w 3"
    environment:
      - DATABASE_NAME
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_HOST
      - REDIS
    depends_on:
      - redis
      - db
    volumes:
      - ./app:/home/app/web

  django-q:
    container_name: where_watch_django_q
    image: where_watch_app
    command: python manage.py qcluster
    volumes:
      - ./app:/home/app/web
    environment:
      - DATABASE_NAME
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_HOST
      - REDIS
    depends_on:
      - redis
      - app
      - db

volumes:
  postgres_data: