version: "3"

services:
  redis:
    image: "redis:alpine"
    restart: always
    command: --port 6378
    expose:
      - 6378

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=where_watch
      - POSTGRES_PASSWORD=where_watch
      - POSTGRES_DB=where_watch
    expose:
      - 5432
  
  web:
    build:
      context: ./where_watch
    container_name: web
    restart: always
    tty: true
    ports:
    - "8006:8006"
    command: "uvicorn main:app --host 0.0.0.0 --port 8006 --reload"
    environment:
      - REDIS=redis://redis:6378
      - DATABASE_URL=postgres://where_watch:where_watch@db:5432/where_watch
    depends_on:
      - redis
      - db
    volumes:
      - ./where_watch:/code

  worker:
    build: ./where_watch
    command: celery --app worker.worker worker --loglevel=info
    volumes:
      - ./where_watch:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6378
      - CELERY_RESULT_BACKEND=redis://redis:6378
    depends_on:
      - redis
      - web
      - db

volumes:
  postgres_data: