name: remote ssh command
on:
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Qwizi/github-action-ssh-docker-compose@master
      name: Docker-Compose Remote Deployment
      with:
          ssh_host: ${{ secrets.HOST }}
          ssh_private_key: ${{ secrets.KEY }}
          ssh_user: ${{ secrets.USER }}
          ssh_port: ${{ secrets.PORT }}
          env_args: ${{ secrets.ENV_ARGS }}
          workspace: where_watch
          docker_compose_filename: docker-compose.prod.yml
          docker_compose_prefix: where_watch